name: MolMiner
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - seaborn
  - openbabel
  - vina
  - swig  # for autodock
  - pip
  - pip:
      - MolMiner
      - notebook
      - pandas
      - rdkit
      - scikit-learn==1.6.1
      - keras
      - scikeras
      - torch
      - optuna
      - scipy
      - tqdm
      - legendkit
      - umap-learn
      - splito
      - safe-mol==0.1.13
      - transformers<5.0.0  # for safe-mol
      - mols2grid
      - prolif
      - xgboost
      - meeko
      - gemmi  # meeko dependency
      - git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3 # AutoDock Tools py3 translation
