[project]
name = "MolMiner"
version = "0.0.1"
readme = "README.md"
description = ""
authors = [
    { name = "Tony Eight Lin", email = "tonyelin@tmu.edu.tw" }
]
license = "MIT"
requires-python = ">=3.11, <3.15"
dependencies = [
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "rdkit>=2025.9.6",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "torch>=2.10.0",
    "keras>=3.13.2",
    "notebook>=7.5.4",
    "optuna>=4.7.0",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
    "legendkit>=0.3.6",
    "umap-learn>=0.5.11",
    "safe-mol==0.1.14",  # check for updates
    "splito>=0.1.4",
    "prolif>=2.1.0",
    "xgboost>=3.2.0",
    "mols2grid>=2.2.0",
    "ipykernel>=7.2.0",
    "transformers<5.0.0", # update to > 5.0.0 when SAFE is updated
    "scikeras>=0.13.0",
    "meeko>=0.6.1",
]

[project.optional-dependencies]
vina = ["vina>=1.2.7"]
shap = ["shap>=0.47.1"]
optuna = ["optuna>=4.2.1"]

[tool.poetry]
packages = [{ include = "mminer" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "py50 (==1.1.0)",
    "shap (>=0.47.1)",
    "optuna (>=4.2.1)"
]
